Support vue v3 template
DevExpress/devextreme-cli pull request #255
Opened 2020-11-10 12:52 UTC by OlegKipchatov

2020-11-10 12:57 UTC, babich-a requested changes

2020-11-10 12:57 UTC, babich-a commented on packages/devextreme-cli/src/applications/application.vue.js
> +var getVersionInfo = require('../utility/prompts/vue-version').getVersionInfo;
const?

2020-12-07 15:54 UTC, babich-a approved these changes

2020-12-10 13:05 UTC, babich-a submitted a review, later dismissed

2020-12-10 13:33 UTC, babich-a approved these changes

2020-12-11 12:59 UTC, dxvladislavvolkov approved these changes

2020-12-11 15:11 UTC, merged